application: lmjrfll
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/1/(.+)
  script: _go_app
  secure: always

- url: /(.+)
  static_files: web/\1
  upload: web/(.*)
  secure: always

- url: /
  script: _go_app
  secure: always
